#Tutorial, April 16, 2024


```{r}
library(tidyverse)
library(janitor)
library(tidycensus)

```


```{r}
census_api_key("4a48d6839c89b310e63a151db25f4787b1b3e5de", install=TRUE, overwrite=TRUE)
```

```{r}

###
# Load ACS variables
###

acs_vars <- load_variables("acs5", year=2020)

###
# Get median household income for Maryland 2020
###

md <- get_acs(geography = "county",
              variables = c(median_income = "B19013_001"),
              state = "MD",
              year = 2020) 


```

#Load Data
```{r}

asian_2020 <- get_acs(geography = "state",
              variables = c(asian_divide = "B02001_005"),
              year = 2020) %>% 
  rename(estimate_2020 = estimate)%>% 
  rename(moe_2020 = moe) 

asian_2010 <- get_acs(geography = "state",
              variables = c(asian_divide = "B02001_005"),
              year = 2010) %>% 
  rename(estimate_2010 = estimate) %>% 
  rename(moe_2010 = moe) 

```


#Join the two data frames together, create a percentage change column
```{r}
asian_2010_2020 <- asian_2010 %>% 
  inner_join(asian_2020, by=c("NAME", "GEOID", "variable")) %>% 
  select(NAME, GEOID, estimate_2010, estimate_2020)

asian_2010_2020 <- asian_2010_2020%>% 
  mutate(pct_change = round((estimate_2020 - estimate_2010)/estimate_2010 *100, digits = 2)) 
  

#You want to avoid this:
#(estimate.y-estimate.x)/(estimate.x)

```

#Pivot Wider
```{r}

# See vignette("pivot") for examples and explanation

# Generate column names from multiple variables
us_rent_income  
  us_rent_income %>%
  pivot_wider(
    names_from = variable,
    values_from = c(estimate, moe)
  )

# You can control whether `names_from` values vary fastest or slowest
# relative to the `values_from` column names using `names_vary`.
us_rent_income %>%
  pivot_wider(
    names_from = variable,
    values_from = c(estimate, moe),
    names_vary = "slowest"
  )


```


#2: Male Population and Pivot Wider

```{r}
#Calculate the males percentage of the total population
# male_population = "B01001_002"
# total_pop = "B01001_001"

population <- get_acs(geography = "state",
              variables = c(male_population = "B01001_002",  total_pop = "B01001_001"),
              year = 2020) %>% 
  rename(state= NAME) %>% 
   pivot_wider(
    names_from = variable,
    values_from = c(estimate, moe),
    names_vary = "slowest"
  ) %>% 
  select(state, estimate_total_pop, estimate_male_population) %>% 
  mutate(pct_male = round(estimate_male_population/estimate_total_pop *100, digits = 2)) %>% 
  arrange(desc(pct_male))



```


