<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Maryland Hospital Emergency Department Wait Times</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/clipboard/clipboard.min.js"></script>
<script src="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/quarto-html/quarto.js"></script>
<script src="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/quarto-html/popper.min.js"></script>
<script src="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/quarto-html/anchor.min.js"></script>
<link href="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Condon_MD_HOSPITAL_DATA_FINAL_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Maryland Hospital Emergency Department Wait Times</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In June, the Maryland Hospitals Association established EDDIE, the Emergency Department Dramatic Improvements Effort, to address hospital wait times in the state. By having each hospital set objectives for lowering emergency department wait times and discharges, EDDIE aims to put Maryland hospitals back on target with the rest of the country. Now, the state has one of the highest average wait times in the country. EDDIE has been collecting monthly data on each Maryland hospital’s average wait times, and I have that data from July 2023 through January 2024, provided by a request to the Maryland Hospital Association.</p>
<p>The data provided by the MHA is fairly large and consists of numerous variables.</p>
<p>ED1 refers to emergency department “arrival to inpatient a admission time” and OP refers outpatients who are discharged into the community for “outpatient ED arrival to discharge time” according to Damiara Smith, a quality fellow for the MHA cost review commission.</p>
<p>For this project, I have chosen to analyze the aggregated psych and non-psych sheet columns to measure hospital patient arrival to emergency department admission on a general basis for all patients, as opposed to psych or non-psych.</p>
<p>Research Questions:</p>
<ol type="1">
<li>What are the average wait times for each hospital across the state in January in hours? As of January, what is month over month wait time for the hospitals with the longst and shortest wait times?</li>
<li>What hospitals in Maryland are seeing the most and least improvement in wait times? 1a. Which 5 hospitals had the lowest percent change since base month? 1b. How many hospitals have had increasing wait times from their base month to January? Which 5 have had the biggest increases?</li>
<li>How does Maryland’s average ED wait time compare to the rest of the country?</li>
<li>Are there any patterns between urban and rural hospitals? What factors affect wait times in each of these areas?</li>
<li>What hospital has seen the most improvement (and least) in its hospital wait times?</li>
</ol>
<p>#Data Notebook</p>
<p>Q1: What hospitals in Maryland are seeing the most and least improvement? Which 5 hospitals had the lowest percent change since August?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#A - Load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install_formats</span>()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(conflicted)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"filter"</span>, <span class="at">winner =</span> <span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[conflicted] Will prefer dplyr::filter over any other package.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"lag"</span>, <span class="at">winner =</span><span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[conflicted] Will prefer dplyr::lag over any other package.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#B - Import the data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>ED1a <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(<span class="st">"EDDIE January FINAL.xlsx"</span>, <span class="at">sheet=</span><span class="st">"ED1a"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...21`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ED1a <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(ED1a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Q1: What are the average wait times for each hospital across the state in January in hours? As of January, what is month over month wait time for the hospitals with the longst and shortest wait times?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Heat map of hospitals</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>january_ed <span class="ot">&lt;-</span> ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name, january_median) <span class="sc">%&gt;%</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">address =</span> abbreviated_name) <span class="sc">%&gt;%</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">41</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Frederick"</span>, <span class="st">"400 W 7th St, Frederick, MD 21701"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Carroll"</span>, <span class="st">"200 Memorial Ave, Westminster, MD 21157"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Atlantic General"</span>, <span class="st">"9733 Healthway Dr, Berlin, MD 21811"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Garrett"</span>, <span class="st">"251 N 4th St, Oakland, MD 21550"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MedStar St. Mary's"</span>, <span class="st">"25500 Point Lookout Rd, Leonardtown, MD 20650"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Calvert"</span>, <span class="st">"100 Hospital Rd, Prince Frederick, MD 20678"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Meritus"</span>, <span class="st">"11116 Medical Campus Rd, Hagerstown, MD 21742"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MedStar Union Memorial"</span>, <span class="st">"201 E University Pkwy, Baltimore, MD 21218"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"ChristianaCare, Union"</span>, <span class="st">"106 Bow St, Elkton, MD 21921"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"TidalHealth Peninsula"</span>, <span class="st">"100 E Carroll St, Salisbury, MD 21801"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"GBMC"</span>, <span class="st">"19801 Observation Dr, Germantown, MD 20876"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Holy Cross Germantown"</span>, <span class="st">"251 N 4th St, Oakland, MD 21550"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"HARFORD MEMORIAL"</span>, <span class="st">" 501 S Union Ave, Havre De Grace, MD 21078"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Ft. Washington"</span>, <span class="st">"11711 Livingston Rd, Fort Washington, MD 20744"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Shady Grove"</span>, <span class="st">"9901 Medical Center Dr, Rockville, MD 20850"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Mercy"</span>, <span class="st">"301 St Paul St, Baltimore, MD 21202"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UPMC Western MD"</span>, <span class="st">"12500 Willowbrook Rd, Cumberland, MD 21502"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Suburban"</span>, <span class="st">"8600 Old Georgetown Rd, Bethesda, MD 20814"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MedStar Montgomery"</span>, <span class="st">"18101 Prince Philip Dr, Olney, MD 20832"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"CHARLES REGIONAL"</span>, <span class="st">"5 Garrett Ave, La Plata, MD 20646"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MedStar Franklin Square"</span>, <span class="st">"9000 Franklin Square Dr, Baltimore, MD 21237"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MedStar Harbor"</span>, <span class="st">"3001 S Hanover St, Baltimore, MD 21225"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Holy Cross"</span>, <span class="st">"1500 Forest Glen Rd, Silver Spring, MD 20910"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Doctors"</span>, <span class="st">"2121 Medical Park Dr, Silver Spring, MD 20902"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"AAMC"</span>, <span class="st">"2001 Medical Pkwy, Annapolis, MD 21401"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MedStar Good Samaritan"</span>, <span class="st">"5601 Loch Raven Blvd, Baltimore, MD 21239"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"MedStar Southern Maryland"</span>, <span class="st">"7503 Surratts Rd, Clinton, MD 20735"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Ascension Saint Agnes"</span>, <span class="st">"900 S Caton Ave, Baltimore, MD 21229"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UM ST. JOSEPH"</span>, <span class="st">"7601 Osler Drive Towson, MD 21204"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UMMC Downtown"</span>, <span class="st">"22 S Greene St, Baltimore, MD 21201"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Northwest"</span>, <span class="st">"5401 Old Court Rd, Randallstown, MD 21133"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UMMC MIDTOWN"</span>, <span class="st">"800 Linden Ave 10th Floor, Baltimore, MD 21201"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Johns Hopkins"</span>, <span class="st">"1800 Orleans St, Baltimore, MD 21287"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UM BWMC"</span>, <span class="st">"301 Hospital Dr, Glen Burnie, MD 21061"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Howard"</span>, <span class="st">"2041 Georgia Ave NW, Washington, DC 20060"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"Sinai"</span>, <span class="st">"2401 W Belvedere Ave, Baltimore, MD 21215"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UPPER CHESAPEAKE"</span>, <span class="st">"500 Upper Chesapeake Dr, Bel Air, MD 21014"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UM CAPITAL REGION"</span>, <span class="st">"901 Harry S Truman Dr, Largo, MD 20774"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"White Oak"</span>, <span class="st">"11890 Healing Wy, Silver Spring, MD 20904"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"JH Bayview"</span>, <span class="st">"4940 Eastern Ave, Baltimore, MD 21224"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"UM SHORE EASTON"</span>, <span class="st">"219 S Washington St, Easton, MD 21601"</span>, january_ed<span class="sc">$</span>address)</span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a><span class="co">#Some of the addresses over rode themsleves (for example in TidalHealth Peninsula hospital, "Carrol" in Caroll Street was overrode by Carroll hospital's address. I fixed this in the csv file before uploading to Data Wrapper)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>DO NOT RUN #install.packages(“ggmap”) library(ggmap) register_google(key = “XXXXX”)</p>
<p>january_ed &lt;- january_ed %&gt;% mutate(location = geocode(address))</p>
<p>Map from data wrapper: https://app.datawrapper.de/map/BTfas/publish</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>january_ed<span class="sc">$</span>address_back <span class="ot">&lt;-</span> january_ed<span class="sc">$</span>address</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>january_ed<span class="ot">&lt;-</span> <span class="fu">separate</span>(january_ed, <span class="at">col =</span> address_back, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"street"</span>, <span class="st">"city"</span>, <span class="st">"zip"</span>), <span class="at">sep =</span> <span class="st">","</span>, <span class="at">extra =</span> <span class="st">"merge"</span>, <span class="at">fill =</span> <span class="st">"right"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">city=</span><span class="fu">str_squish</span>(city))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>january_ed <span class="ot">&lt;-</span> <span class="fu">separate</span>(january_ed, <span class="at">col =</span> zip, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"state"</span>, <span class="st">"zip"</span>), <span class="at">sep =</span> <span class="st">"MD "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Missing pieces filled with `NA` in 1 rows [35].</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>january_ed <span class="ot">&lt;-</span>january_ed <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state=</span> <span class="st">"MD"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>january_ed <span class="ot">&lt;-</span>january_ed <span class="sc">%&gt;%</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">median_hour =</span> <span class="fu">round</span>(january_median<span class="sc">/</span><span class="dv">60</span>, <span class="dv">2</span>))</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>january_ed <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(january_ed)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(january_ed, <span class="st">"january_ed.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Hospital with longest wait time in January</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>longest <span class="ot">&lt;-</span> ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name, january_median) <span class="sc">%&gt;%</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(january_median))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co">#In January, University of Maryland Shore Eastern in Easton, Md. (Talbot County) had the longest wait time at 1770.5 minutes, or 29.5 hours.</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>longest_graph <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(<span class="st">"EDDIE January FINAL.xlsx"</span>, <span class="at">sheet=</span><span class="st">"UMES"</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>longest_graph <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(longest_graph)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>longest_graph <span class="ot">&lt;-</span> longest_graph <span class="sc">%&gt;%</span> </span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month_order=</span>month) </span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>longest_graph <span class="ot">&lt;-</span> longest_graph <span class="sc">%&gt;%</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month_order =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>     month <span class="sc">==</span> <span class="st">"June"</span> <span class="sc">~</span> <span class="st">"1"</span>,</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    month <span class="sc">==</span> <span class="st">"July"</span> <span class="sc">~</span> <span class="st">"2"</span>,</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>     month <span class="sc">==</span> <span class="st">"August"</span> <span class="sc">~</span> <span class="st">"3"</span>,</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>     month <span class="sc">==</span> <span class="st">"September"</span> <span class="sc">~</span> <span class="st">"4"</span>,</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>    month <span class="sc">==</span> <span class="st">"October"</span> <span class="sc">~</span> <span class="st">"5"</span>,</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>     month <span class="sc">==</span> <span class="st">"November"</span> <span class="sc">~</span> <span class="st">"6"</span>,</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>     month <span class="sc">==</span> <span class="st">"December"</span> <span class="sc">~</span> <span class="st">"7"</span>,</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>     month <span class="sc">==</span> <span class="st">"January"</span> <span class="sc">~</span> <span class="st">"8"</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>   ))</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>longest_graph <span class="ot">&lt;-</span> longest_graph <span class="sc">%&gt;%</span> </span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">median_hour =</span> <span class="fu">round</span>(median<span class="sc">/</span><span class="dv">60</span>,<span class="dv">2</span>))</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>longest_graph<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">factor</span>(longest_graph<span class="sc">$</span>month, <span class="at">levels =</span>  <span class="fu">c</span>(<span class="st">"June"</span>, <span class="st">"July"</span>, <span class="st">"August"</span>, <span class="st">"September"</span>, <span class="st">"October"</span>, <span class="st">"November"</span>, <span class="st">"December"</span>, <span class="st">"January"</span>))</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>longest_graph <span class="sc">%&gt;%</span> </span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>month, <span class="at">y=</span>median_hour, <span class="at">weight=</span>median_hour, <span class="at">fill=</span>month)) <span class="sc">+</span></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()<span class="sc">+</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>median_hour), <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"Median Time (in hours) by Month for UM Shore Eastern"</span>,</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median time in hours"</span>,</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"UM Eastern Shore's hospital, based in Easton, Md., had the longest ER waittime in the state in January. </span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a><span class="st">    This shows median emergency department wait times for eight months at the hospital.</span></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a><span class="st">    Source: Maryland Hospital Association Cost Review Commisssion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Condon_MD_HOSPITAL_DATA_FINAL_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Hospital with shortest wait time in January</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>shortest <span class="ot">&lt;-</span> ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name, january_median) <span class="sc">%&gt;%</span> </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(january_median)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">#In January, Atlantic General, located in Berlin, Md (Worcester County) had the  shortest wait time at 193 minutes, or about 3.2 hours.</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>shortest_graph <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(<span class="st">"EDDIE January FINAL.xlsx"</span>, <span class="at">sheet=</span><span class="st">"AG"</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>shortest_graph <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(shortest_graph)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>shortest_graph <span class="ot">&lt;-</span> shortest_graph <span class="sc">%&gt;%</span> </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month_order=</span>month) </span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"June"</span>, <span class="st">"1"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"July"</span>, <span class="st">"2"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order<span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"August"</span>, <span class="st">"3"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"September"</span>, <span class="st">"4"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"October"</span>, <span class="st">"5"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"November"</span>, <span class="st">"6"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"December"</span>, <span class="st">"7"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month_order <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"January"</span>, <span class="st">"8"</span>, shortest_graph<span class="sc">$</span>month_order)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>shortest_graph <span class="ot">&lt;-</span> shortest_graph <span class="sc">%&gt;%</span> </span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">median_hour =</span> <span class="fu">round</span>(median<span class="sc">/</span><span class="dv">60</span>, <span class="dv">2</span>))</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>shortest_graph<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">factor</span>(shortest_graph<span class="sc">$</span>month, <span class="at">levels =</span>  <span class="fu">c</span>(<span class="st">"June"</span>, <span class="st">"July"</span>, <span class="st">"August"</span>, <span class="st">"September"</span>, <span class="st">"October"</span>, <span class="st">"November"</span>, <span class="st">"December"</span>, <span class="st">"January"</span>))</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>shortest_graph <span class="sc">%&gt;%</span> </span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>month, <span class="at">y=</span>median_hour, <span class="at">weight=</span>median_hour, <span class="at">fill=</span>month)) <span class="sc">+</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()<span class="sc">+</span></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>median_hour), <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"Median Time (in hours) by Month for Atlantic General"</span>,</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median time in hours"</span>,</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Atlantic General hospital, based in Berlin, Md., had the shortest ER waittime in the state in January. </span></span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a><span class="st">    This shows median emergency department wait times for eight months at the hospital.</span></span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a><span class="st">    Source: Maryland Hospital Association Cost Review Commisssion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Condon_MD_HOSPITAL_DATA_FINAL_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Findings from charts:</p>
<p>Atlantic General in Berlin, Md. had the highest median wait time in January, and UM Eastern Shore in Easton, Md. had the longest median wait time that month.</p>
<p>Atlantic General had a significantly shorter average wait time (of about 3.2 hours in its emergency department, which is still long) than UM Eastern Shore at 29.5 hours. The variation in Eastern Shore’s times was also a significantly larger range. I was shocked to see that from November to January, UM Eastern Shore’s wait time increased by almost 1000 minutes on average.</p>
<p>From this data, I would want to talk to someone at each hospital to ask what was going on. I’d also be interested in talking to people who visited UM Eastern Shore and waited 1700 minutes (over 28 hours) to be seen in an emergency room.</p>
<p>I also want to look into UM Eastern Shores’ outlined objectives and goals for decreasing times that are required to be stated under the new EDDIE program. How does the hospital’s objectives relate to the reality of its extremely flunctuating wait times for patients.</p>
<p>Q2: What hospitals in Maryland are seeing the most and least improvement in wait times? 1a. Which 5 hospitals had the lowest percent change since base month? 1b. How many hospitals have had increasing wait times from their base month to January? Which 5 have had the biggest increases?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Pct_change <span class="ot">&lt;-</span> ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name, august_median, january_median) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>Pct_change <span class="ot">&lt;-</span> Pct_change <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name,august_median, january_median) <span class="sc">%&gt;%</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">base_august=</span> (january_median <span class="sc">-</span> august_median)<span class="sc">/</span>august_median <span class="sc">*</span><span class="dv">100</span>) </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>Pct_change_top5 <span class="ot">&lt;-</span> Pct_change <span class="sc">%&gt;%</span> </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(base_august) <span class="sc">%&gt;%</span> </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Answer: White Oak in Silver Spring, Md. (at -427.8%), UMMC Midtwon in Baltimore (at -15.4), Mercy Hospital in Baltimore (at -14.4%,), Atlantic General in Berlin, Md. (at -12.7%) and Shady Grove in Rockville (at -10.5%) had the lowest percent change, and thus the biggest decreases in hospital wait times since their base month.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>How many hospitals have had increasing wait times from their base month to January? Which 5 have had the biggest increases?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>Pct_change2 <span class="ot">&lt;-</span> ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name, august_median, january_median) </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Answer: 33 hospitals have increasing wait times since their base month.</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>Pct_change2 <span class="ot">&lt;-</span> ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name,august_median, january_median) <span class="sc">%&gt;%</span> </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">base_august=</span> (january_median <span class="sc">-</span> august_median)<span class="sc">/</span>august_median <span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(base_august)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Answer: Of the 33 hospitals, the five with the highest increasing wait times were Upper Chesapeake in Bel Air, Md. (at 136.6%), MedStar Good Samaritan in Baltimore (at 84.9%), Carroll Hospital in Westminster, Md. (at 76.3%), Union ChristianaCare in Elkton, Md. (at 62.6%) and Holy Cross Germantown in Oakland, Md. (at 60.5%).</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Q3: How does Maryland’s average ED wait time compare to the rest of the country?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>national_ed <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(<span class="st">"Timely_and_Effective_Care-State.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Data from Census for Medicare and Medicaid services: https://data.cms.gov/provider-data/dataset/apyc-v239 </span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>national_ed_op18c <span class="ot">&lt;-</span> national_ed <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(measure_id <span class="sc">==</span> <span class="st">"OP_18c"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">score =</span> <span class="fu">gsub</span>(<span class="st">"[^0-9.]"</span>, <span class="st">""</span>, score)) <span class="sc">%&gt;%</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">score =</span> <span class="fu">as.numeric</span>(score))</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co">#I used OP_18C because this is the outpatient category that aggregates psych and non-psych admits.</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>top10<span class="ot">&lt;-</span> national_ed_op18c <span class="sc">%&gt;%</span> </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(score)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(national_ed_op18c<span class="sc">$</span>score, <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="co">#= 267.3077</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 267.3077</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This data set, which collected wait times up until May 30, 2023, put Maryland at number 3 for the longest average emergency department times in the country. Maryland's average wait time of 409 minutes, or almost 7 hours, was only shorter than DC and Vermont. The average of all of these median times was 267.3077 or 4.5 hours.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Map of 10 states with longest ED wait times</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>top10<span class="sc">$</span>state <span class="ot">&lt;-</span> <span class="fu">factor</span>(top10<span class="sc">$</span>state, <span class="at">levels =</span>  <span class="fu">c</span>(<span class="st">"DC"</span>, <span class="st">"VT"</span>, <span class="st">"MD"</span>, <span class="st">"DE"</span>, <span class="st">"RI"</span>, <span class="st">"MA"</span>, <span class="st">"PR"</span>, <span class="st">"TN"</span>, <span class="st">"NY"</span>, <span class="st">"GA"</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>top10 <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>state, <span class="at">y=</span>score, <span class="at">weight=</span>score, <span class="at">fill=</span>score)) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_col</span>()<span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>score), <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"States with longest Emergency Department Wait Time"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"State"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average (median) time in minutes patients spent in the emergency department before leaving from the visit"</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"source: Census for Medicare and Medicaid Services"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Condon_MD_HOSPITAL_DATA_FINAL_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Q4: Are there any patterns between urban and rural hospitals? What factors affect wait times in each of these areas?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Defining rural and urban (not rural) by MD Dept of Health definition</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="ot">&lt;-</span> january_ed <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">county=</span>city) </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="ot">&lt;-</span> urban_rural <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">county =</span> <span class="fu">case_when</span>(</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Berlin"</span> <span class="sc">~</span> <span class="st">"Worcester"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Oakland"</span> <span class="sc">~</span> <span class="st">"Garrett"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Baltimore"</span> <span class="sc">~</span> <span class="st">"Balt City"</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Leonardtown"</span> <span class="sc">~</span> <span class="st">"St. Marys"</span>,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Hagerstown"</span> <span class="sc">~</span> <span class="st">"Washington"</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Elkton"</span> <span class="sc">~</span> <span class="st">"Cecil"</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    county <span class="sc">==</span> <span class="st">"Salisbury"</span> <span class="sc">~</span> <span class="st">"Wicomico"</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Germantown"</span> <span class="sc">~</span> <span class="st">"Montgomery"</span>,</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Havre De Grace"</span> <span class="sc">~</span> <span class="st">"Harford"</span>,</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Rockville"</span> <span class="sc">~</span> <span class="st">"Montgomery"</span>,</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Cumberland"</span> <span class="sc">~</span> <span class="st">"Allegany"</span>,</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Silver Spring"</span> <span class="sc">~</span> <span class="st">"Montgomery"</span>,</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Bethesda"</span> <span class="sc">~</span> <span class="st">"Montgomery"</span>,</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"La Plata"</span> <span class="sc">~</span> <span class="st">"Charles"</span>,</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Fort Washington"</span> <span class="sc">~</span> <span class="st">"Prince George's"</span>,</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Olney"</span> <span class="sc">~</span> <span class="st">"Montgomery"</span>,</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Glen Burnie"</span> <span class="sc">~</span> <span class="st">"Anne Arundel"</span>,</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Columbia"</span> <span class="sc">~</span> <span class="st">"Howard"</span>,</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Bel Air"</span> <span class="sc">~</span> <span class="st">"Harford"</span>,</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Largo"</span> <span class="sc">~</span> <span class="st">"Prince George's"</span>,</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Easton"</span> <span class="sc">~</span> <span class="st">"Talbot"</span>,</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Randallstown"</span> <span class="sc">~</span> <span class="st">"Balt County"</span>,</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Annapolis"</span> <span class="sc">~</span> <span class="st">"Anne Arundel"</span>,</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Clinton"</span> <span class="sc">~</span> <span class="st">"Prince George's"</span>,</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>     county <span class="sc">==</span> <span class="st">"Towson"</span> <span class="sc">~</span> <span class="st">"Balt County"</span>,</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>     <span class="cn">TRUE</span> <span class="sc">~</span> county  </span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>   ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>According to MD Dept of health (https://health.maryland.gov/pophealth/Pages/Rural-health.aspx): “Allegany, Calvert, Caroline, Carroll, Cecil, Charles, Dorchester, Frederick, Garrett, Harford, Kent, Queen Anne’s, Somerset, St.&nbsp;Mary’s, Talbot, Washington, Wicomico, and Worcester.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(urban_rural)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(urban_rural)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="ot">&lt;-</span> urban_rural <span class="sc">%&gt;%</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">define =</span> <span class="fu">case_when</span>(</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Allegany'</span>  <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Cecil'</span> <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Charles'</span>  <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Federick'</span>  <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Garrett'</span> <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Harford'</span>  <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'St. Marys'</span>  <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Talbot'</span> <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Washington'</span>  <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Wicomico'</span> <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>   county <span class="sc">==</span> <span class="st">'Worcester'</span>  <span class="sc">~</span> <span class="st">"rural"</span>,</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>   <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"not_rural"</span>))</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="ot">&lt;-</span> urban_rural <span class="sc">%&gt;%</span> </span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(abbreviated_name, january_median, address, county, define)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>rural_hospitals <span class="ot">&lt;-</span> urban_rural <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(define <span class="sc">==</span> <span class="st">"rural"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(rural_hospitals<span class="sc">$</span>january_median) <span class="co">#= 682.25 minutes (or 11.3 hours)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 698.1538</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>not_rural_hospitals <span class="ot">&lt;-</span> urban_rural <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(define <span class="sc">==</span> <span class="st">"not_rural"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(not_rural_hospitals<span class="sc">$</span>january_median) <span class="co">#= 711.2759 minutes (or 11.8 hours)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 704.9286</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#There is not a significant difference in averages for January wait times for rural and non rural hospitals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="ot">&lt;-</span> urban_rural <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name2 =</span> <span class="fu">substr</span>(<span class="fu">str_replace_all</span>(<span class="fu">tolower</span>(abbreviated_name), <span class="st">"[^[:alnum:]]"</span>, <span class="st">""</span>), <span class="dv">1</span>, <span class="dv">10</span>))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>urban_rural <span class="sc">%&gt;%</span> </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">reorder</span>(name2, january_median), <span class="at">y=</span>january_median, <span class="at">weight=</span>january_median, <span class="at">fill=</span>define)) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()<span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>january_median), <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">angle =</span> <span class="dv">90</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"Median Time for hospitals in January (by rural and non"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Hospital Name"</span>,</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"median time in minutes"</span>,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"source: Maryland Hospital Association Cost Review Commisssion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Condon_MD_HOSPITAL_DATA_FINAL_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Although the two hospitals with the highest average wait times in January were rural, the hospitals with the two lowest wait times were also rural. There seems to be no causal relationship between wait times and rural or urban hospitals.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Q5: What hospital has seen the most improvement in its hospital wait times?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compared from August to January with each month's difference to account for seasonal variations</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>ED1a <span class="ot">&lt;-</span> ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">change =</span> (august_median <span class="sc">-</span> july_median) <span class="sc">+</span> (september_median <span class="sc">-</span> august_median) <span class="sc">+</span> (october_median <span class="sc">-</span> september_median) <span class="sc">+</span> (november_median <span class="sc">-</span> october_median) <span class="sc">+</span> (december_median <span class="sc">-</span> november_median) <span class="sc">+</span> (january_median <span class="sc">-</span> december_median))</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>ED1a <span class="sc">%&gt;%</span> </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(change) <span class="sc">%&gt;%</span> </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  hospital_id abbreviated_name june_median rolling_median_june_ytd july_median
1      210038     UMMC MIDTOWN         685                   705.0         849
2      210034   MedStar Harbor         458                   529.5         553
3      210008            Mercy         526                   575.0         577
4      210016        White Oak        1251                  1283.0         865
5      210061 Atlantic General         210                   206.0         218
  rolling_median_july_ytd august_median rolling_median_august_ytd
1                     705           800                       723
2                     533           474                       532
3                     575           575                       569
4                    1203          1143                      1196
5                     200           221                       205
  september_median rolling_median_september_ytd october_median
1            658.5                          722            768
2            910.0                          977            513
3            407.0                          504            450
4            855.0                         1125           1328
5            212.0                          206            195
  rolling_median_october_ytd november_median rolling_median_november_ytd
1                        732             560                         713
2                        532             402                         511
3                        497             423                         489
4                       1114            1210                        1115
5                        203             189                         202
  december_median rolling_median_december_ytd january_median
1           698.0                       710.0            677
2           441.5                       482.5            457
3           466.0                       486.0            492
4           794.0                       786.0            825
5           216.0                       204.0            193
  rolling_median_january_ytd average_median_attainment
1                      698.0                  711.9375
2                      467.5                  526.0625
3                      482.0                  489.5000
4                      739.0                 1033.8750
5                      203.0                  206.7500
  change_from_base_month_to_latest_improvement x21 change
1                                           -8   0   -172
2                                           -1   0    -96
3                                          -34   0    -85
4                                         -426   0    -40
5                                          -17   0    -25</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#UMMC Midtown in Baltimore saw the biggest improvement, dropping an aggregated 172 minutes from August through January. UM Eastern Shore in Easton added 819.5 minutes from August through January.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Conclusion:</p>
<ol type="1">
<li>What are the average wait times for each hospital across the state in January in hours? As of January, what is month over month wait time for the hospitals with the longst and shortest wait times?</li>
</ol>
<p>Please see each hospital in January on this Data Wrapper: Map from data wrapper: https://app.datawrapper.de/map/BTfas/publish In January, University of Maryland Shore Eastern in Easton, Md. (Talbot County) had the longest wait time at 1770.5 minutes, or 29.5 hours. See line 203 for the graph of each month from June through August. #In January, Atlantic General, located in Berlin, Md (Worcester County) had the shortest wait time at 193 minutes, or about 3.2 hours. See line 242 for the graph of each month from June through August.</p>
<ol start="2" type="1">
<li>What hospitals in Maryland are seeing the most and least improvement in wait times? 1a. Which 5 hospitals had the biggest improvement in wait times measured by the lowest percent change since base month?</li>
</ol>
<p>White Oak in Silver Spring, Md. (at -427.8%), UMMC Midtwon in Baltimore (at -15.4%), Mercy Hospital in Baltimore (at -14.4%,), Atlantic General in Berlin, Md. (at -12.7%) and Shady Grove in Rockville (at -10.5%) had the lowest percent change, and thus the biggest decreases in hospital wait times since their base month.</p>
<p>2b. How many hospitals have had increasing wait times from their base month to January? Which 5 have had the biggest increases?</p>
<p>Answer: Of the 33 hospitals, the five with the highest increasing wait times were Upper Chesapeake in Bel Air, Md. (at 136.6%), MedStar Good Samaritan in Baltimore (at 84.9%), Carroll Hospital in Westminster, Md. (at 76.3%), Union ChristianaCare in Elkton, Md. (at 62.6%) and Holy Cross Germantown in Oakland, Md. (at 60.5%).</p>
<ol start="3" type="1">
<li>How does Maryland’s average ED wait time compare to the rest of the country?</li>
</ol>
<p>The data from Census for Medicare and Medicaid services, which collected wait times up until May 30, 2023, put Maryland at number 3 for the longest average emergency department times in the country. Maryland’s average wait time of 409 minutes, or almost 7 hours, was only shorter than DC and Vermont.</p>
<ol start="4" type="1">
<li>Are there any patterns between urban and rural hospitals? What factors affect wait times in each of these areas?</li>
</ol>
<p>There is not a significant difference in averages for january wait times for rural and non rural hospitals. (Please see graph on 362) Although the two hospitals with the highest average wait times in January were rural, the hospitals with the two lowest wait times were also rural. There seems to be no causal relationship between wait times and rural or urban hospitals.</p>
<ol start="5" type="1">
<li>What hospital has seen the most improvement (and least) in its hospital wait times?</li>
</ol>
<p>UMMC Midtown in Baltimore saw the biggest improvement, dropped 172 minutes from August through January. UM Eastern Shore in Easton added 819.5 minutes from August through January.</p>
<p>250-word summary of the most interesting newsworthy findings so far: I think the biggest takeaway from all of this is that the high hospital wait times is a state-wide problem. There doesn’t seem to be one hospital as an outlier for the high wait times. Even Atlantic General in Worcester County that had the shortest wait time at 3.2 hours in January still had a very long wait time. In 2023, according to the Medicard data, the US average median wait time was 267 minutes, or 4.45 hours. In January in Maryland, only Atlantic and Garret fell below this number. So 39 out of 41 Maryland hospitals had a median time above the average national median wait time. The hospitals with the most and least improvements in wait times as a percentage also saw no type of pattern, as they were all pretty scattered across the state.</p>
<p>There also was not even a pattern between the rural and urban hospitals. This indicates that there is an issue in how the Maryland hospital system as a whole responds to emergency care, as one cannot blame high volumes of people or other factors which may be attributed to demographic factors like neighborhood type.</p>
<p>UM Eastern Shore is a standout problem as having the highest wait time in January and also having the largest change from August through January in minutes.</p>
<p>All of this indicates to me that the data points to a clear issue in hospitals that is present across the state, not just in one area or just in rural or non-rural hospitals.</p>
<p>On-the-ground reporting would have to be done in order to really find out what is going on with Maryland hospitals and to figure out what is broken in the system.</p>
<p>Story Memo/Pitch:</p>
<p>Headline: Maryland hospital wait times see little improvement, despite new state commission Author: Emily R. Condon Pitch: In June, the Maryland Hospitals Association established EDDIE, the Emergency Department Dramatic Improvements Effort, to address hospital wait times in the state. By having each hospital set objectives for lowering emergency department wait times and discharges, EDDIE aims to put Maryland hospitals back on target with the rest of the country. This analysis of data from EDDIE shows that hospital wait times in the state are still suffering. There doesn’t seem to be one hospital as an outlier for the high wait times. Even Atlantic General in Worcester County that had the shortest wait time at 3.2 hours in January still had a very long wait time. In 2023, according to the Medicard data, the US average median wait time was 267 minutes, or 4.45 hours. In January in Maryland, only Atlantic and Garret fell below this number. So 39 out of 41 Maryland hospitals had a median time above the average national median wait time. The hospitals with the most and least improvements in wait times as a percentage also saw no type of pattern, as they were all pretty scattered across the state. While reporting has been done on this, solutions-oriented articles lack. I would do on-the-ground reporting and find hospitals who are seeing some improvements to talk to them about what they are doing to improve emergency department waittimes. Estimated Word Count: 800 words Potential photos / videos: Photos of people in Emergency Rooms are difficult due to HIPPA laws, so outside shots of hospitals Potential graphics: Graphs of each hospital, MD median wait time compares to other states, a statewide map with each hospital and their most recent media wait time</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>